# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\x1f\n\x07Numbers\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x05\x32I\n\nCalculator\x12\x1a\n\x03\x61\x64\x64\x12\x08.Numbers\x1a\x07.Result\"\x00\x12\x1f\n\x08multiply\x12\x08.Numbers\x1a\x07.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMBERS']._serialized_start=20
  _globals['_NUMBERS']._serialized_end=51
  _globals['_RESULT']._serialized_start=53
  _globals['_RESULT']._serialized_end=76
  _globals['_CALCULATOR']._serialized_start=78
  _globals['_CALCULATOR']._serialized_end=151
# @@protoc_insertion_point(module_scope)
